### ISSUE TITLE
muy bien hecho 

### ISSUE THREAD

**Issue by velazcopolo** [greyzeids/card-random-generator#1]
esta excelente, lo unico que no me ha convencido del todo es que le usuario tenga que escribir el tipo de medida, ela parte de la funcion habria sido mejor colocar al final de manera concatenado un + px

este es tu codigo:
card.style.width = width ? width : card.style.width;
    card.style.height = height ? height : card.style.height;

habira sido mejor:
card.style.width = width ? width : card.style.width +"px";
    card.style.height = height ? height : card.style.height +"px";

ya que nosotros sabemos que eso iria en pixels, o en EM, o en VM, pero un usuario normal no lo sabria aunque ahi en el placeholder lo has especificado, lo mejor es darle la menor probabilidad de falla al usuario

**Comment by greyzeids** [comment]
Solucionado Carlos, gracias por la critica constructiva! jaja, al final tuve que hacerlo asi:

function cardSize() {
    let width = parseInt(document.getElementById("cardWidth").value);
    let height = parseInt(document.getElementById("cardHeight").value);

    let card = document.getElementById("card");

    card.style.width = width ? width + "px" : card.style.width;
    card.style.height = height ? height + "px" : card.style.height;
}

**Comment by greyzeids** [comment]
Fixed
